# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-11 07:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200123_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 11, 7, 18, 17, 692543), verbose_name='Date Published'),
        ),
    ]
