# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-11 07:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200211_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 11, 7, 19, 9, 382696), verbose_name='Date Published'),
        ),
    ]
