# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-11 17:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200211_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 11, 17, 4, 4, 944928), verbose_name='Date Published'),
        ),
    ]
