# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-18 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200217_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialcategory',
            old_name='tutorial_summary',
            new_name='category_summary',
        ),
    ]
